Servidor e Conexão com banco de dados
ComunidadeCafeina/plataforma-back pull request #1
Opened 2021-11-19 13:51 UTC by marianavns

Estrutura do servidor criada e conexão com o banco de dados estabelecida.

2021-11-24 22:58 UTC, IsabellaSoares requested changes
Mari, arrasou no trabalho! 🚀 Pedi algumas alterações, para seguirmos os modelos fornecidos nas descrições das tarefas. E deixei também algumas sugestões sobre a arquitetura do projeto, mas não são obrigatórias e podemos falar com mais calma sobre elas.

2021-11-24 22:58 UTC, IsabellaSoares commented on server/infra/database_ENV.js
> +})
Apaixonada por essa documentação ❤️

2021-11-24 22:58 UTC, IsabellaSoares commented on server/route/projectsRoute.js
> +// router.delete('/:id')
Precisamos deixar esses comentários aqui?

2021-11-24 22:58 UTC, IsabellaSoares commented on server/route/socialNetworksRoute.js
> +// router.delete('/:id')
Sobre os comentários aqui também...

2021-11-24 22:58 UTC, IsabellaSoares commented on server/server.js
> +app.use('/', require('./route/socialNetworksRoute'))
Podemos criar um arquivo de exports globais em `./route`, como um `./route/index.js`, para fazemos esse "use routes" em uma única linha. O que acha?

2021-11-24 22:58 UTC, IsabellaSoares commented on database/create.sql
> +    brandicon char(50) NOT NULL,
```suggestion
    id serial primary key NOT NULL,
    brandIcon char(50) NOT NULL,
```

2021-11-24 22:58 UTC, IsabellaSoares commented on database/create.sql
> +    descriptio char(200) NOT NULL,
```suggestion
    description char(200) NOT NULL,
```

2021-11-24 22:58 UTC, IsabellaSoares commented on database/create.sql
> +    texto char(50) NOT NULL,
```suggestion
    text char(50) NOT NULL,
```

2021-12-01 17:49 UTC, marianavns commented on server/infra/database_ENV.js
> +})
obrigada, Isa! <3

2021-12-01 17:58 UTC, marianavns commented on server/route/projectsRoute.js
> +// router.delete('/:id')
Consertei, tá indo no próximo PR!

2021-12-01 18:00 UTC, marianavns commented on server/server.js
> +app.use('/', require('./route/socialNetworksRoute'))
Isa, deixei separado mais por questão de responsividade mesmo, acho que fica melhor pra dar manutenção depois. Mas, como ainda estou meio que no começo, tô 100% aberta pra gente mudar isso!

2021-12-01 18:10 UTC, marianavns commented on database/create.sql
> +    descriptio char(200) NOT NULL,
Consertei! estava dando palavra reservada no meu VSCode.

2021-12-01 18:10 UTC, marianavns commented on database/create.sql
> +    texto char(50) NOT NULL,
Consertei! Estava dando palavra reservada no meu VSCode.

2021-12-01 18:10 UTC, marianavns commented on database/create.sql
> +    brandicon char(50) NOT NULL,
Consertei!

2021-12-02 13:09 UTC, IsabellaSoares approved these changes

2021-12-09 13:59 UTC, merged